name: Publish nuget
on: 
  workflow_dispatch
  
jobs:
  deploy:
    name: Publish nuget
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository (Latest)
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # Now run whatever you want:
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      #- name: Pack
      #  run: dotnet pack --configuration Release
      #- name: NuGet push
      #  run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.NUGET_PACKAGE_PAT }} --source nuget.org --skip-duplicate
